[workspace]
channels = ["pypi" ,"conda-forge"]
name = "PaperPublishgit"
platforms = ["linux-64","win-64"]
version = "0.1.0"

[tasks]
jupserve = "jupyter lab --no-browser --ip=0.0.0.0"

[dependencies]
python = ">=3.13.11,<3.14"
openpyxl = ">=3.1.5,<4"


[pypi-dependencies]
jupyter = ">=1.1.1, <2"
jupyterlab = ">=4.5.3, <5"
ipython = ">=9.10.0, <10"
pandas = ">=3.0.0, <4"
numpy = ">=2.4.1, <3"
dask = ">=2026.1.1, <2027"
scipy = ">=1.17.0, <2"
scikit-image = ">=0.26.0, <0.27"
scikit-learn = ">=1.8.0, <2"
seaborn = ">=0.13.2, <0.14"
matplotlib = ">=3.10.8, <4"
bioio = ">=3.2.0, <4"
bioio-nd2 = ">=1.6.2, <2"
bioio-czi = ">=2.4.2, <3"
bioio-ome-tiff = ">=1.4.0, <2"
bioio-ome-zarr = ">=3.2.1, <4"
bioio-bioformats = ">=1.3.2, <2"
bioio-tifffile = ">=1.3.0, <2"
bioio-lif = ">=1.4.2, <2"
bioio-imageio = ">=1.3.0, <2"
magicgui = ">=0.10.1, <0.11"
qtpy = ">=2.4.3, <3"
tqdm = ">=4.67.1, <5"
ffmpeg = ">=1.4, <2"
holoviews = ">=1.22.1, <2"

