name: snBase
channels:
  - anaconda
  - conda-forge
dependencies:
  - _libavif_api=1.3.0=h57928b3_0
  - anyio=4.9.0=pyh29332c3_0
  - aom=3.9.1=he0c23c2_0
  - appdirs=1.4.4=pyhd8ed1ab_1
  - argon2-cffi=23.1.0=pyhd8ed1ab_1
  - argon2-cffi-bindings=21.2.0=py311he736701_5
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.3.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_5
  - backports.functools_lru_cache=2.0.0=pyhd8ed1ab_1
  - beautifulsoup4=4.13.4=pyha770c72_0
  - blas=1.0=mkl
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - blosc=1.21.5=hbd69f2e_1
  - bottleneck=1.5.0=py311h0a17f05_0
  - brotli=1.0.9=hcfcfb64_9
  - brotli-bin=1.0.9=hcfcfb64_9
  - brotli-python=1.0.9=py311h12c1d0e_9
  - brotlipy=0.7.0=py311he736701_1007
  - bzip2=1.0.8=h2466b09_7
  - c-blosc2=2.15.0=h90144bb_0
  - ca-certificates=2025.4.26=h4c7d964_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2025.4.26=pyhd8ed1ab_0
  - cffi=1.17.1=py311he736701_0
  - cfitsio=3.470=h0af3d06_7
  - charls=2.2.0=h39d44d4_0
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - click=8.2.1=pyh7428d3b_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.2=py311h3257749_0
  - cpython=3.11.12=py311hd8ed1ab_0
  - cryptography=45.0.2=py311hfd75b31_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cytoolz=1.0.1=py311he736701_0
  - dask-core=2025.5.1=pyhd8ed1ab_0
  - dav1d=1.2.1=hcfcfb64_0
  - debugpy=1.8.14=py311hda3d55a_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - docstring_parser=0.16=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_1
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.0=he0c23c2_0
  - ffmpeg=4.3.1=ha925a31_0
  - flit-core=3.12.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=hbde0cde_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.58.0=py311h5082efb_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freeglut=3.4.0=hd77b12b_0
  - freetype=2.12.1=hdaf720e_2
  - fsspec=2025.5.0=pyhd8ed1ab_0
  - gettext=0.22.5=h5728263_3
  - gettext-tools=0.22.5=h5a7288d_3
  - giflib=5.2.2=h64bf75a_0
  - glib=2.80.2=h0df6a38_0
  - glib-tools=2.80.2=h2f9d560_0
  - gst-plugins-base=1.22.9=h001b923_1
  - gstreamer=1.22.9=hb4038d2_1
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.2.0=pyhd8ed1ab_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=70.1=h0e60522_0
  - idna=3.10=pyhd8ed1ab_1
  - imagecodecs=2024.9.22=py311h8c33f1c_1
  - imageio=2.37.0=pyhfb79c49_0
  - importlib-metadata=8.6.1=pyha770c72_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - intel-openmp=2023.2.0=h57928b3_50497
  - ipykernel=6.29.5=pyh4bbf305_0
  - ipython=9.2.0=pyhca29cf9_0
  - ipython_genutils=0.2.0=pyhd8ed1ab_2
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.7=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.0=pyhd8ed1ab_0
  - jpeg=9e=hcfcfb64_3
  - json5=0.12.0=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py311h1ea47a8_1
  - jsonschema=4.23.0=pyhd8ed1ab_1
  - jsonschema-specifications=2025.4.1=pyh29332c3_0
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_1
  - jupyter=1.1.1=pyhd8ed1ab_1
  - jupyter-lsp=2.2.5=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_console=6.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh5737063_1
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.16.0=pyhe01879c_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.2=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - jupyterlab_widgets=3.0.15=pyhd8ed1ab_0
  - jxrlib=1.1=hcfcfb64_3
  - kiwisolver=1.4.7=py311h3257749_0
  - krb5=1.20.1=heb0366b_0
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lazy_loader=0.4=pyhd8ed1ab_2
  - lcms2=2.16=h62be587_1
  - lerc=4.0.0=h6470a55_1
  - libaec=1.1.3=h63175ca_0
  - libasprintf=0.22.5=h5728263_3
  - libasprintf-devel=0.22.5=h5728263_3
  - libavif=1.3.0=hf2698fe_0
  - libavif16=1.3.0=hf2698fe_0
  - libblas=3.9.0=20_win64_mkl
  - libbrotlicommon=1.0.9=hcfcfb64_9
  - libbrotlidec=1.0.9=hcfcfb64_9
  - libbrotlienc=1.0.9=hcfcfb64_9
  - libcblas=3.9.0=20_win64_mkl
  - libclang=15.0.7=default_h3a3e6c3_5
  - libclang13=15.0.7=default_hf64faad_5
  - libcurl=8.1.2=h68f0423_0
  - libdeflate=1.22=h2466b09_0
  - libexpat=2.7.0=he0c23c2_0
  - libffi=3.4.6=h537db12_1
  - libgettextpo=0.22.5=h5728263_3
  - libgettextpo-devel=0.22.5=h5728263_3
  - libglib=2.80.2=h0df6a38_0
  - libhwloc=2.11.2=default_hc8275d1_1000
  - libiconv=1.18=h135ad9c_1
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - liblapack=3.9.0=20_win64_mkl
  - liblzma=5.8.1=h2466b09_1
  - liblzma-devel=5.8.1=h2466b09_1
  - libogg=1.3.5=h2466b09_1
  - libopus=1.5.2=h2466b09_0
  - libpng=1.6.43=h19919ed_0
  - libsodium=1.0.18=h8d14728_1
  - libsqlite=3.49.2=h67fdade_0
  - libssh2=1.11.0=h7dfc565_0
  - libtiff=4.7.0=h404307b_0
  - libvorbis=1.3.7=h0e60522_0
  - libwebp=1.5.0=h3b0e114_0
  - libwebp-base=1.5.0=h3b0e114_0
  - libxcb=1.16=h013a479_1
  - libxml2=2.12.7=h283a6d9_1
  - libxslt=1.1.39=h3df6e99_0
  - libzlib=1.2.13=h2466b09_6
  - libzopfli=1.0.3=h0e60522_0
  - llvmlite=0.42.0=py311h5bc0dda_1
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4-c=1.9.4=hcfcfb64_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - magicgui=0.10.0=pyhd8ed1ab_0
  - markupsafe=3.0.2=py311h5082efb_1
  - matplotlib-base=3.10.1=py311h8f1b1e4_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mistune=3.1.3=pyh29332c3_0
  - mkl=2023.2.0=h6a75c08_50497
  - mkl-service=2.4.1=py311h130b7e8_1
  - mkl_fft=1.3.10=py311h1d15ed5_1
  - mkl_random=1.2.8=py311h97a4ddd_0
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclassic=1.3.1=pyhe01879c_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert=7.16.6=hb482800_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbconvert-pandoc=7.16.6=hed9df3c_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.4.2=pyh267e887_2
  - notebook=7.4.2=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numba=0.59.1=py311h2c0921f_0
  - numexpr=2.10.1=mkl_py311haeafc90_2
  - numpy=1.26.4=py311hdab7c0b_0
  - numpy-base=1.26.4=py311hd01c5d8_0
  - openh264=2.6.0=hb17fa0b_0
  - openjpeg=2.5.2=h3d672ee_0
  - openpyxl=3.1.5=py311ha68e1ae_1
  - openssl=3.5.0=ha4e3fda_1
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.2.3=py311hcf9f919_3
  - pandoc=3.7.0.1=h57928b3_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_1
  - partd=1.4.2=pyhd8ed1ab_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre=8.45=h0e60522_0
  - pcre2=10.43=h17e33f8_0
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py311hea0d53e_1
  - pip=25.1.1=pyh8b19718_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.3.8=pyhe01879c_0
  - ply=3.11=pyhd8ed1ab_3
  - pooch=1.8.2=pyhd8ed1ab_1
  - prometheus_client=0.22.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - prompt_toolkit=3.0.51=hd8ed1ab_0
  - psutil=7.0.0=py311he736701_0
  - psygnal=0.13.0=pyhd8ed1ab_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pthreads-win32=2.9.1=h2466b09_4
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyconify=0.2.1=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyopenssl=25.1.0=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyqt=5.15.9=py311h125bc19_5
  - pyqt5-sip=12.12.2=py311h12c1d0e_5
  - pyrsistent=0.20.0=py311he736701_1
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.11.9=h631f459_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-fastjsonschema=2.21.1=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=7_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - pywavelets=1.8.0=py311h0a17f05_0
  - pywin32=307=py311hda3d55a_3
  - pywinpty=2.0.15=py311hda3d55a_0
  - pyyaml=6.0.2=py311h5082efb_2
  - pyzmq=26.2.0=py311h484c95c_1
  - qhull=2020.2=hc790b64_5
  - qt-main=5.15.8=h720456b_6
  - qt-webengine=5.15.9=h5bd16bc_7
  - qtconsole=5.6.1=pyhd8ed1ab_1
  - qtconsole-base=5.6.1=pyha770c72_1
  - qtpy=2.4.3=pyhd8ed1ab_0
  - qtwebkit=5.212=h992fabe_8
  - rav1e=0.7.1=ha073cba_3
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.3=pyhd8ed1ab_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.25.1=py311hc4022dc_0
  - scikit-image=0.25.2=py311hcf9f919_0
  - scikit-learn=1.6.1=py311hdcb8d17_0
  - scipy=1.15.2=py311h99d06ae_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - send2trash=1.8.3=pyh5737063_1
  - setuptools=80.8.0=pyhff2d567_0
  - sip=6.7.12=py311h12c1d0e_0
  - six=1.17.0=pyhd8ed1ab_0
  - skan=0.12.1=pyhd8ed1ab_0
  - snappy=1.2.1=h500f7fa_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.7=pyhd8ed1ab_0
  - sqlite=3.49.2=h2466b09_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.4=py311h0a17f05_0
  - superqt=0.7.3=pyhb6d5dde_0
  - svt-av1=3.0.2=he0c23c2_0
  - tbb=2021.13.0=h62715c5_1
  - terminado=0.18.1=pyh5737063_0
  - testpath=0.6.0=pyhd8ed1ab_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h5226925_1
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.2.1=pyhd8ed1ab_1
  - toolz=1.0.0=pyhd8ed1ab_1
  - tornado=6.5=py311he736701_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20250516=pyhd8ed1ab_0
  - typing-extensions=4.13.2=h0e9735f_0
  - typing_extensions=4.13.2=pyh29332c3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.22621.0=h57928b3_1
  - unicodedata2=16.0.0=py311he736701_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.4.0=pyhd8ed1ab_0
  - vc=14.3=h2b53caa_26
  - vc14_runtime=14.42.34438=hfd919c2_26
  - vs2015_runtime=14.42.34438=h7142326_26
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.14=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - winpty=0.4.3=4
  - wrapt=1.17.2=py311he736701_0
  - x264=1!164.3095=h8ffe710_2
  - x265=3.5=h2d74725_3
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xz=5.8.1=h208afaa_1
  - xz-tools=5.8.1=h2466b09_1
  - yaml=0.2.5=h8ffe710_2
  - zeromq=4.3.5=he0c23c2_3
  - zfp=1.0.1=he0c23c2_2
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.2.13=h2466b09_6
  - zlib-ng=2.0.7=hcfcfb64_0
  - zstandard=0.23.0=py311he736701_2
  - zstd=1.5.6=h0ea2cb4_0
  - pip:
      - opencv-python==4.8.0.74
      - tifffile==2023.7.18
prefix: C:\Miniforge\envs\snBase
